# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false # Desactiva los issues en blanco para forzar el uso de tus plantillas

contact_links:
  - name: 💬 Comunidad en WhatsApp
    url: https://chat.whatsapp.com/JmcjxMqqH5NDmh5APFWahM
    about: Únete para consultas rápidas, noticias y networking con la comunidad local.

  - name: 🎮 Servidor de Discord
    url: https://discord.com/invite/TV5tHvdUKt
    about: Ideal para soporte técnico detallado, voz y convivencia en proyectos específicos.

  - name: 🌐 Sitio Web Oficial de la comunidad
    url: https://pylapaz.org
    about: Conoce más sobre nuestra historia, eventos pasados y misión.
